# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_window_prototype.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(20, 15, 20, 15)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.surnameEdit = QtWidgets.QLineEdit(Dialog)
        self.surnameEdit.setObjectName("surnameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.surnameEdit)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.genderEdit = QtWidgets.QComboBox(Dialog)
        self.genderEdit.setEditable(True)
        self.genderEdit.setObjectName("genderEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.genderEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.birthdateEdit = QtWidgets.QDateEdit(Dialog)
        self.birthdateEdit.setCalendarPopup(True)
        self.birthdateEdit.setObjectName("birthdateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthdateEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pseriesEdit = QtWidgets.QLineEdit(Dialog)
        self.pseriesEdit.setMaxLength(4)
        self.pseriesEdit.setObjectName("pseriesEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pseriesEdit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pnumberEdit = QtWidgets.QLineEdit(Dialog)
        self.pnumberEdit.setMaxLength(6)
        self.pnumberEdit.setObjectName("pnumberEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pnumberEdit)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setInputMask("9999999999")
        self.phoneEdit.setObjectName("phoneEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phoneEdit)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.roomEdit = QtWidgets.QSpinBox(Dialog)
        self.roomEdit.setMinimum(1)
        self.roomEdit.setObjectName("roomEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.roomEdit)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.childrenEdit = QtWidgets.QComboBox(Dialog)
        self.childrenEdit.setEditable(False)
        self.childrenEdit.setObjectName("childrenEdit")
        self.childrenEdit.addItem("")
        self.childrenEdit.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.childrenEdit)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.residentsEdit = QtWidgets.QSpinBox(Dialog)
        self.residentsEdit.setMinimum(1)
        self.residentsEdit.setObjectName("residentsEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.residentsEdit)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.arrivalEdit = QtWidgets.QDateEdit(Dialog)
        self.arrivalEdit.setCalendarPopup(True)
        self.arrivalEdit.setObjectName("arrivalEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.arrivalEdit)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.departureEdit = QtWidgets.QDateEdit(Dialog)
        self.departureEdit.setCalendarPopup(True)
        self.departureEdit.setObjectName("departureEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.departureEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setMinimumSize(QtCore.QSize(90, 23))
        self.clearButton.setMaximumSize(QtCore.QSize(150, 50))
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout.addWidget(self.clearButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setMaximumSize(QtCore.QSize(150, 50))
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)

        self.retranslateUi(Dialog)
        self.childrenEdit.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Внести изменения в базу"))
        self.label_13.setText(_translate("Dialog", "Данные постояльца"))
        self.label.setText(_translate("Dialog", "Имя"))
        self.label_2.setText(_translate("Dialog", "Фамилия"))
        self.label_3.setText(_translate("Dialog", "Гендер"))
        self.label_4.setText(_translate("Dialog", "Дата рождения"))
        self.birthdateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_5.setText(_translate("Dialog", "Паспорт серия"))
        self.pseriesEdit.setInputMask(_translate("Dialog", "9999"))
        self.label_6.setText(_translate("Dialog", "Паспорт номер"))
        self.pnumberEdit.setInputMask(_translate("Dialog", "999999"))
        self.label_7.setText(_translate("Dialog", "Телефон"))
        self.label_8.setText(_translate("Dialog", "Номер"))
        self.label_9.setText(_translate("Dialog", "С детьми"))
        self.childrenEdit.setItemText(0, _translate("Dialog", "Нет"))
        self.childrenEdit.setItemText(1, _translate("Dialog", "Да"))
        self.label_10.setText(_translate("Dialog", "Постояльцев"))
        self.label_11.setText(_translate("Dialog", "Дата заселения"))
        self.arrivalEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_12.setText(_translate("Dialog", "Дата выселения"))
        self.departureEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.clearButton.setText(_translate("Dialog", "Очистить поля"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
